auth_enabled: false # for demonstration only!

server:
  http_listen_port: 3100
  log_level: warn
  log_format: json

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /tmp/loki

storage_config:
  # configures storing index in an object store in a prometheus TSDB-like format.
  tsdb_shipper:
    # Directory where ingesters would write index files which would then be
    # uploaded by shipper to configured storage
    active_index_directory: "/loki/index"

    # Cache location for restoring index files from storage for queries
    cache_location: "/loki/index_cache"
    cache_ttl: 24h # TTL for index files restored in cache for queries

  # configuring filesystem backend; for other supported stores see https://grafana.com/docs/loki/latest/configure/storage/#object-storage
  # for a real-world, production deployment, pick a reliable object store like s3, gcs, etc.
  filesystem:
    # directory to store chunks in
    directory: "/loki/chunks"

# Log retention in Loki is achieved through the Compactor (https://grafana.com/docs/loki/latest/get-started/components/#compactor)
compactor:
  retention_enabled: true
  delete_request_store: filesystem

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  ring:
    kvstore:
      store: inmemory

limits_config:
  retention_period: 15d # retention period to apply to stored data

# configures the chunk index schema and where it is stored.
schema_config:
  # configures what index schemas should be used for from specific time periods.
  configs:
    - from: 2025-01-01          # since when this config should take effect; see: https://grafana.com/docs/loki/latest/configure/storage/#schema-config
      store: tsdb               # storage used for index
      object_store: filesystem  # storage used for chunks
      schema: v13
      index:
        prefix: index_
        period: 24h

pattern_ingester:
  enabled: true
