name: waf-observability
services:
  grafana:
    image: grafana/grafana:12.4
    depends_on:
      - prometheus
      - loki
      - tempo
      - pyroscope
    ports:
      - "3000:3000"
    environment:
      - GF_PLUGINS_PREINSTALL_SYNC=grafana-pyroscope-app
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_LOG_MODE=console
      - GF_LOG_LEVEL=warn
      - GF_LOG_CONSOLE_FORMAT=json
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/dashboards:/etc/grafana/dashboards:ro
      - grafana-storage:/var/lib/grafana
  prometheus:
    image: prom/prometheus:v3.7.3
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-remote-write-receiver
      - --log.level=warn
      - --log.format=json
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-storage:/prometheus
  loki:
    image: grafana/loki:3.6.3
    command:
      - -config.file=/etc/loki/config.yaml
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/config.yaml
      - loki-storage:/loki
  tempo:
    image: grafana/tempo:2.9.0
    user: root # to temporarily fix permission issues; do not use on prod
    volumes:
      - ./tempo/tempo.yml:/etc/tempo/config.yaml
      - tempo-storage:/tmp/tempo
    command: -config.file=/etc/tempo/config.yaml
  pyroscope:
    image: grafana/pyroscope:1.17.0
    command:
      - -log.level=warn
      - -log.format=json
  alloy:
    image: grafana/alloy:v1.11.3
    depends_on:
      - prometheus
      - loki
      - tempo
      - pyroscope
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/config.alloy
    volumes:
      - ./alloy/config.alloy:/etc/config.alloy:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run/udev/data:/run/udev/data:ro
      - alloy-storage:/var/lib/alloy/data
    ports:
      - "12345:12345"
      - "4317:4317"
      - "4318:4318"
      - "4319:4319"
volumes:
  grafana-storage:
  prometheus-storage:
  loki-storage:
  tempo-storage:
  alloy-storage:
