server:
  http_listen_port: 3200
  log_level: warn
  log_format: json

# Distributors receive spans and forward them to the appropriate ingesters.
# The following configuration enables OpenTelemetry receiver
distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

# The ingester is responsible for batching up traces and pushing them to TempoDB.
ingester:
  max_block_duration: 5m

# Compactors stream blocks from the storage backend, combine them and write them back.
compactor:
  compaction:
    compaction_window: 1h

querier:
  frontend_worker:
    frontend_address: 127.0.0.1:9095

# Storage block configures TempoDB. See https://grafana.com/docs/tempo/latest/configuration/#storage
storage:
  trace:
    backend: local
    local: # configuration block for local storage
      path: /tmp/tempo/blocks
    wal:   # configuration block for the Write Ahead Log (WAL)
      path: /tmp/tempo/wal

metrics_generator:
  storage:
    path: /tmp/tempo/generator
  ring:
    kvstore:
      store: inmemory
